-- Public game item IDs and observed recipe uses; Forever 1.60.1 build 70205.
-- Extracted October 3, 2026. Partial discovery snapshot; see README.md.
local _, addon = ...
addon.catalogSeed = {
    [118] = {Tailoring = true},
    [159] = {Cooking = true, Engineering = true, FirstAid = true},
    [723] = {Cooking = true},
    [729] = {Cooking = true},
    [730] = {Alchemy = true, Cooking = true},
    [731] = {Cooking = true},
    [765] = {Alchemy = true, Herbalism = true},
    [769] = {Cooking = true},
    [774] = {Blacksmithing = true, Engineering = true},
    [783] = {Leatherworking = true},
    [785] = {Alchemy = true, Cooking = true},
    [814] = {Engineering = true, Tailoring = true},
    [818] = {Blacksmithing = true, Engineering = true},
    [929] = {Tailoring = true},
    [1015] = {Cooking = true},
    [1080] = {Cooking = true},
    [1081] = {Cooking = true},
    [1179] = {Cooking = true},
    [1205] = {Cooking = true},
    [1206] = {Blacksmithing = true, Engineering = true, Leatherworking = true},
    [1210] = {Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [1251] = {FirstAid = true},
    [1288] = {Alchemy = true, FirstAid = true},
    [1468] = {Cooking = true, FirstAid = true},
    [1475] = {Cooking = true, FirstAid = true},
    [1529] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [1645] = {Cooking = true},
    [1705] = {Blacksmithing = true, Engineering = true},
    [1708] = {Cooking = true},
    [2251] = {Cooking = true},
    [2289] = {Enchanting = true},
    [2312] = {Leatherworking = true},
    [2313] = {Leatherworking = true},
    [2318] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Skinning = true, Tailoring = true},
    [2319] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Skinning = true, Tailoring = true},
    [2320] = {Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [2321] = {FirstAid = true, Leatherworking = true, Skinning = true, Tailoring = true},
    [2324] = {Leatherworking = true, Tailoring = true},
    [2325] = {Leatherworking = true, Tailoring = true},
    [2447] = {Alchemy = true, Cooking = true, FirstAid = true, Herbalism = true},
    [2449] = {Alchemy = true},
    [2450] = {Alchemy = true, FirstAid = true},
    [2452] = {Alchemy = true, Cooking = true, Enchanting = true},
    [2453] = {Alchemy = true, FirstAid = true},
    [2454] = {Leatherworking = true},
    [2455] = {Leatherworking = true, Tailoring = true},
    [2456] = {Alchemy = true},
    [2457] = {Leatherworking = true},
    [2458] = {Leatherworking = true},
    [2459] = {Blacksmithing = true, Enchanting = true, Leatherworking = true},
    [2570] = {Engineering = true},
    [2589] = {Blacksmithing = true, Engineering = true, FirstAid = true, Tailoring = true},
    [2592] = {Engineering = true, FirstAid = true, Tailoring = true},
    [2594] = {FirstAid = true},
    [2596] = {Cooking = true, FirstAid = true},
    [2604] = {Tailoring = true},
    [2605] = {Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [2672] = {Cooking = true},
    [2673] = {Cooking = true},
    [2674] = {Cooking = true},
    [2675] = {Cooking = true},
    [2677] = {Cooking = true},
    [2678] = {Cooking = true, FirstAid = true},
    [2686] = {FirstAid = true},
    [2692] = {Cooking = true, FirstAid = true},
    [2723] = {FirstAid = true},
    [2770] = {Mining = true},
    [2771] = {Mining = true},
    [2772] = {Enchanting = true, Mining = true},
    [2775] = {Enchanting = true, Mining = true},
    [2776] = {Mining = true},
    [2835] = {Blacksmithing = true, Engineering = true, Mining = true},
    [2836] = {Blacksmithing = true, Engineering = true},
    [2838] = {Blacksmithing = true, Engineering = true, Mining = true},
    [2840] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Mining = true},
    [2841] = {Blacksmithing = true, Engineering = true},
    [2842] = {Blacksmithing = true, Engineering = true, Mining = true, Tailoring = true},
    [2863] = {Blacksmithing = true},
    [2870] = {Blacksmithing = true},
    [2880] = {Blacksmithing = true, Engineering = true},
    [2886] = {Cooking = true},
    [2894] = {Cooking = true},
    [2924] = {Cooking = true},
    [2934] = {Leatherworking = true},
    [2996] = {Engineering = true, Tailoring = true},
    [2997] = {Leatherworking = true, Tailoring = true},
    [3013] = {Enchanting = true},
    [3030] = {Engineering = true},
    [3172] = {Cooking = true},
    [3173] = {Cooking = true},
    [3174] = {Cooking = true, FirstAid = true},
    [3182] = {Leatherworking = true, Tailoring = true},
    [3355] = {Alchemy = true},
    [3356] = {Alchemy = true, Enchanting = true, Leatherworking = true},
    [3357] = {Alchemy = true, Cooking = true, FirstAid = true},
    [3358] = {Alchemy = true},
    [3369] = {Alchemy = true},
    [3371] = {Alchemy = true, Enchanting = true, FirstAid = true, Fishing = true},
    [3372] = {Alchemy = true, Enchanting = true, FirstAid = true},
    [3383] = {Leatherworking = true, Tailoring = true},
    [3385] = {Leatherworking = true},
    [3389] = {Leatherworking = true},
    [3390] = {Leatherworking = true},
    [3391] = {Blacksmithing = true, Leatherworking = true},
    [3404] = {Cooking = true},
    [3466] = {Blacksmithing = true},
    [3470] = {Blacksmithing = true},
    [3478] = {Blacksmithing = true},
    [3486] = {Blacksmithing = true},
    [3575] = {Alchemy = true, Blacksmithing = true, Engineering = true, Mining = true, Skinning = true},
    [3576] = {Mining = true},
    [3577] = {Blacksmithing = true, Engineering = true, Tailoring = true},
    [3667] = {Cooking = true},
    [3685] = {Cooking = true},
    [3712] = {Cooking = true},
    [3713] = {Cooking = true, FirstAid = true},
    [3730] = {Cooking = true},
    [3731] = {Cooking = true},
    [3818] = {Alchemy = true, Cooking = true},
    [3819] = {Alchemy = true, Enchanting = true},
    [3820] = {Alchemy = true},
    [3821] = {Alchemy = true, Cooking = true},
    [3823] = {Blacksmithing = true},
    [3824] = {Alchemy = true, Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [3827] = {Leatherworking = true, Tailoring = true},
    [3829] = {Blacksmithing = true, Enchanting = true, Engineering = true, Tailoring = true},
    [3857] = {Mining = true},
    [3858] = {Alchemy = true, Mining = true},
    [3859] = {Blacksmithing = true, Engineering = true},
    [3860] = {Alchemy = true, Blacksmithing = true, Engineering = true},
    [3864] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [4096] = {Leatherworking = true},
    [4231] = {Leatherworking = true},
    [4232] = {Leatherworking = true},
    [4233] = {Leatherworking = true},
    [4234] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Skinning = true, Tailoring = true},
    [4235] = {Leatherworking = true},
    [4236] = {Leatherworking = true},
    [4243] = {Leatherworking = true},
    [4246] = {Leatherworking = true},
    [4253] = {Leatherworking = true},
    [4255] = {Blacksmithing = true},
    [4265] = {Leatherworking = true},
    [4289] = {Leatherworking = true},
    [4291] = {FirstAid = true, Leatherworking = true, Tailoring = true},
    [4304] = {Blacksmithing = true, Engineering = true, FirstAid = true, Leatherworking = true, Tailoring = true},
    [4305] = {Engineering = true, Leatherworking = true, Tailoring = true},
    [4306] = {Engineering = true, FirstAid = true, Tailoring = true},
    [4320] = {Tailoring = true},
    [4337] = {Engineering = true, Leatherworking = true, Tailoring = true},
    [4338] = {Blacksmithing = true, Engineering = true, FirstAid = true, Leatherworking = true, Tailoring = true},
    [4339] = {Engineering = true, Tailoring = true},
    [4340] = {Leatherworking = true, Tailoring = true},
    [4341] = {Tailoring = true},
    [4342] = {Alchemy = true, Tailoring = true},
    [4357] = {Engineering = true},
    [4359] = {Engineering = true},
    [4360] = {Engineering = true},
    [4361] = {Engineering = true},
    [4363] = {Engineering = true},
    [4364] = {Engineering = true},
    [4368] = {Engineering = true},
    [4371] = {Engineering = true},
    [4375] = {Engineering = true},
    [4377] = {Engineering = true},
    [4380] = {Engineering = true},
    [4382] = {Engineering = true},
    [4385] = {Engineering = true},
    [4387] = {Engineering = true},
    [4389] = {Engineering = true},
    [4394] = {Engineering = true},
    [4397] = {Engineering = true},
    [4399] = {Engineering = true},
    [4400] = {Engineering = true},
    [4402] = {Alchemy = true, Cooking = true, Engineering = true},
    [4404] = {Engineering = true},
    [4405] = {Engineering = true},
    [4407] = {Engineering = true},
    [4461] = {Leatherworking = true},
    [4470] = {Cooking = true, Enchanting = true, FirstAid = true, Fishing = true, Herbalism = true, Leatherworking = true, Skinning = true, Tailoring = true},
    [4536] = {Cooking = true},
    [4589] = {Tailoring = true},
    [4603] = {Cooking = true},
    [4605] = {Enchanting = true},
    [4611] = {Engineering = true},
    [4625] = {Alchemy = true, Enchanting = true, Tailoring = true},
    [4655] = {Cooking = true},
    [5051] = {Cooking = true},
    [5082] = {Leatherworking = true},
    [5116] = {Leatherworking = true},
    [5373] = {Leatherworking = true},
    [5465] = {Cooking = true},
    [5466] = {Cooking = true},
    [5467] = {Cooking = true},
    [5468] = {Cooking = true},
    [5469] = {Cooking = true},
    [5470] = {Cooking = true},
    [5471] = {Cooking = true},
    [5498] = {Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [5500] = {Blacksmithing = true, Enchanting = true, Leatherworking = true, Tailoring = true},
    [5503] = {Cooking = true},
    [5504] = {Cooking = true},
    [5507] = {Engineering = true},
    [5633] = {Leatherworking = true},
    [5635] = {Alchemy = true, Blacksmithing = true},
    [5637] = {Alchemy = true, Blacksmithing = true, Cooking = true, Enchanting = true, Leatherworking = true},
    [5784] = {Leatherworking = true, Skinning = true},
    [5785] = {Leatherworking = true},
    [5966] = {Blacksmithing = true},
    [6037] = {Blacksmithing = true, Enchanting = true, Engineering = true, Mining = true, Tailoring = true},
    [6048] = {Enchanting = true, Tailoring = true},
    [6217] = {Enchanting = true},
    [6260] = {Leatherworking = true, Tailoring = true},
    [6261] = {Leatherworking = true, Tailoring = true},
    [6289] = {Cooking = true},
    [6291] = {Cooking = true, Fishing = true},
    [6303] = {Cooking = true},
    [6308] = {Cooking = true},
    [6317] = {Cooking = true},
    [6338] = {Enchanting = true},
    [6358] = {Alchemy = true},
    [6359] = {Alchemy = true},
    [6361] = {Cooking = true},
    [6362] = {Cooking = true},
    [6370] = {Alchemy = true, Enchanting = true},
    [6371] = {Alchemy = true, Enchanting = true, Tailoring = true},
    [6452] = {FirstAid = true},
    [6453] = {FirstAid = true},
    [6470] = {Leatherworking = true},
    [6471] = {Leatherworking = true},
    [6522] = {Alchemy = true, Cooking = true},
    [6530] = {Engineering = true},
    [6662] = {Leatherworking = true},
    [6889] = {Cooking = true},
    [7067] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [7068] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Tailoring = true},
    [7069] = {Alchemy = true, Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [7070] = {Alchemy = true, Blacksmithing = true, FirstAid = true, Leatherworking = true, Tailoring = true},
    [7071] = {Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [7072] = {Tailoring = true},
    [7075] = {Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true},
    [7076] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [7077] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [7078] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [7079] = {Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [7080] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, FirstAid = true, Leatherworking = true, Tailoring = true},
    [7081] = {Blacksmithing = true, Enchanting = true},
    [7082] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [7191] = {Engineering = true},
    [7286] = {Leatherworking = true},
    [7287] = {Leatherworking = true},
    [7387] = {Engineering = true},
    [7392] = {Enchanting = true, Leatherworking = true},
    [7428] = {Leatherworking = true},
    [7909] = {Blacksmithing = true, Enchanting = true, Engineering = true},
    [7910] = {Blacksmithing = true, Engineering = true, Tailoring = true},
    [7911] = {Mining = true},
    [7912] = {Blacksmithing = true, Engineering = true},
    [7966] = {Blacksmithing = true},
    [7971] = {Blacksmithing = true, Enchanting = true, Leatherworking = true, Tailoring = true},
    [7972] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Tailoring = true},
    [7974] = {Cooking = true},
    [8146] = {Blacksmithing = true, Cooking = true, Leatherworking = true},
    [8150] = {Cooking = true, Engineering = true, Leatherworking = true},
    [8151] = {Enchanting = true, Engineering = true, Leatherworking = true},
    [8152] = {Enchanting = true, Leatherworking = true},
    [8153] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [8154] = {Leatherworking = true},
    [8165] = {Leatherworking = true},
    [8167] = {Leatherworking = true},
    [8168] = {Blacksmithing = true, Leatherworking = true},
    [8169] = {Leatherworking = true},
    [8170] = {Blacksmithing = true, Enchanting = true, Engineering = true, FirstAid = true, Leatherworking = true, Tailoring = true},
    [8171] = {Leatherworking = true},
    [8172] = {Leatherworking = true},
    [8173] = {Leatherworking = true},
    [8343] = {FirstAid = true, Leatherworking = true, Tailoring = true},
    [8365] = {Cooking = true, Fishing = true},
    [8368] = {Leatherworking = true},
    [8544] = {FirstAid = true},
    [8766] = {Cooking = true},
    [8831] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Herbalism = true, Tailoring = true},
    [8836] = {Alchemy = true, Herbalism = true},
    [8838] = {Alchemy = true, Cooking = true, Enchanting = true, FirstAid = true},
    [8839] = {Alchemy = true},
    [8845] = {Alchemy = true},
    [8846] = {Alchemy = true},
    [8925] = {Alchemy = true, Enchanting = true, FirstAid = true, Fishing = true, Herbalism = true},
    [8949] = {Leatherworking = true},
    [8951] = {Leatherworking = true},
    [8959] = {Cooking = true},
    [9060] = {Engineering = true},
    [9061] = {Cooking = true, Engineering = true},
    [9206] = {Leatherworking = true},
    [9210] = {Tailoring = true},
    [9224] = {Enchanting = true},
    [9260] = {Alchemy = true},
    [9262] = {Alchemy = true, Engineering = true},
    [10026] = {Engineering = true},
    [10284] = {Cooking = true},
    [10285] = {Engineering = true, Tailoring = true},
    [10286] = {Alchemy = true, Engineering = true, Tailoring = true},
    [10290] = {Tailoring = true},
    [10308] = {Enchanting = true},
    [10500] = {Engineering = true},
    [10502] = {Engineering = true},
    [10505] = {Engineering = true},
    [10507] = {Engineering = true},
    [10518] = {Engineering = true},
    [10543] = {Engineering = true},
    [10546] = {Engineering = true},
    [10558] = {Engineering = true},
    [10559] = {Engineering = true},
    [10560] = {Engineering = true},
    [10561] = {Engineering = true},
    [10576] = {Engineering = true},
    [10577] = {Engineering = true},
    [10586] = {Engineering = true},
    [10588] = {Engineering = true},
    [10592] = {Engineering = true},
    [10620] = {Alchemy = true, Mining = true},
    [10647] = {Engineering = true},
    [10648] = {Engineering = true},
    [10938] = {Blacksmithing = true, Enchanting = true},
    [10939] = {Enchanting = true},
    [10940] = {Blacksmithing = true, Enchanting = true, Leatherworking = true},
    [10978] = {Enchanting = true},
    [10998] = {Enchanting = true},
    [11040] = {Tailoring = true},
    [11082] = {Enchanting = true, Tailoring = true},
    [11083] = {Alchemy = true, Enchanting = true, Leatherworking = true},
    [11084] = {Enchanting = true},
    [11128] = {Enchanting = true},
    [11134] = {Enchanting = true, Tailoring = true},
    [11135] = {Enchanting = true},
    [11137] = {Enchanting = true, Leatherworking = true, Tailoring = true},
    [11138] = {Enchanting = true},
    [11139] = {Blacksmithing = true, Enchanting = true},
    [11144] = {Enchanting = true},
    [11174] = {Enchanting = true},
    [11175] = {Enchanting = true, Engineering = true, Tailoring = true},
    [11176] = {Alchemy = true, Enchanting = true, Leatherworking = true, Tailoring = true},
    [11177] = {Enchanting = true},
    [11178] = {Enchanting = true, Tailoring = true},
    [11184] = {Blacksmithing = true},
    [11185] = {Blacksmithing = true},
    [11186] = {Blacksmithing = true},
    [11188] = {Blacksmithing = true},
    [11291] = {Cooking = true, Enchanting = true},
    [11370] = {Mining = true},
    [11371] = {Blacksmithing = true, Engineering = true},
    [11382] = {Blacksmithing = true, Enchanting = true},
    [11754] = {Blacksmithing = true, Enchanting = true, Leatherworking = true},
    [12037] = {Cooking = true},
    [12184] = {Cooking = true},
    [12202] = {Cooking = true},
    [12203] = {Cooking = true},
    [12204] = {Cooking = true},
    [12205] = {Cooking = true},
    [12206] = {Cooking = true},
    [12207] = {Cooking = true},
    [12208] = {Cooking = true},
    [12223] = {Cooking = true},
    [12359] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Mining = true},
    [12360] = {Blacksmithing = true, Engineering = true, Mining = true, Tailoring = true},
    [12361] = {Blacksmithing = true, Engineering = true, Leatherworking = true},
    [12363] = {Alchemy = true, Enchanting = true, Engineering = true},
    [12364] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [12365] = {Blacksmithing = true, Engineering = true, Mining = true},
    [12607] = {Leatherworking = true},
    [12644] = {Blacksmithing = true},
    [12655] = {Blacksmithing = true, Engineering = true, Mining = true},
    [12662] = {Blacksmithing = true, Tailoring = true},
    [12735] = {Enchanting = true},
    [12753] = {Blacksmithing = true, Enchanting = true, Leatherworking = true},
    [12784] = {Blacksmithing = true},
    [12790] = {Blacksmithing = true},
    [12794] = {Blacksmithing = true},
    [12796] = {Blacksmithing = true},
    [12797] = {Blacksmithing = true},
    [12799] = {Blacksmithing = true, Engineering = true, Leatherworking = true},
    [12800] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [12803] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [12804] = {Alchemy = true, Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [12808] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true, Tailoring = true},
    [12809] = {Blacksmithing = true, Enchanting = true, Leatherworking = true, Tailoring = true},
    [12810] = {Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [12811] = {Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [12938] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Leatherworking = true, Tailoring = true},
    [13180] = {Enchanting = true},
    [13422] = {Alchemy = true},
    [13423] = {Alchemy = true, Leatherworking = true},
    [13444] = {Leatherworking = true},
    [13458] = {Enchanting = true},
    [13463] = {Alchemy = true},
    [13464] = {Alchemy = true, FirstAid = true},
    [13465] = {Alchemy = true, Cooking = true, Herbalism = true},
    [13466] = {Alchemy = true},
    [13467] = {Alchemy = true, Enchanting = true, Engineering = true},
    [13468] = {Alchemy = true, Enchanting = true, Tailoring = true},
    [13510] = {Alchemy = true, Blacksmithing = true},
    [13511] = {Alchemy = true, Blacksmithing = true},
    [13512] = {Alchemy = true, Blacksmithing = true},
    [13513] = {Alchemy = true},
    [13754] = {Cooking = true},
    [13755] = {Cooking = true},
    [13756] = {Cooking = true},
    [13758] = {Cooking = true},
    [13759] = {Cooking = true},
    [13760] = {Cooking = true},
    [13888] = {Cooking = true},
    [13889] = {Cooking = true},
    [13890] = {Cooking = true},
    [13893] = {Cooking = true},
    [13926] = {Blacksmithing = true, Enchanting = true, Tailoring = true},
    [14044] = {Leatherworking = true},
    [14047] = {Enchanting = true, Engineering = true, FirstAid = true, Herbalism = true, Leatherworking = true, Tailoring = true},
    [14048] = {Fishing = true, Leatherworking = true, Tailoring = true},
    [14227] = {Engineering = true, Leatherworking = true, Tailoring = true},
    [14256] = {Leatherworking = true, Tailoring = true},
    [14341] = {Leatherworking = true, Tailoring = true},
    [14342] = {Leatherworking = true, Tailoring = true},
    [14343] = {Enchanting = true, Tailoring = true},
    [14344] = {Enchanting = true, Engineering = true, Tailoring = true},
    [14530] = {FirstAid = true},
    [15407] = {Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [15408] = {Leatherworking = true},
    [15409] = {Leatherworking = true},
    [15410] = {Alchemy = true, Leatherworking = true},
    [15412] = {Leatherworking = true},
    [15414] = {Leatherworking = true},
    [15415] = {Leatherworking = true},
    [15416] = {Leatherworking = true},
    [15417] = {Blacksmithing = true, Leatherworking = true},
    [15419] = {Leatherworking = true},
    [15420] = {Leatherworking = true},
    [15422] = {Leatherworking = true},
    [15423] = {Leatherworking = true},
    [15564] = {Leatherworking = true},
    [15992] = {Engineering = true},
    [15994] = {Engineering = true},
    [16000] = {Engineering = true},
    [16005] = {Engineering = true},
    [16006] = {Engineering = true},
    [16202] = {Enchanting = true},
    [16203] = {Alchemy = true, Enchanting = true, Engineering = true, Tailoring = true},
    [16204] = {Enchanting = true, Engineering = true},
    [16206] = {Enchanting = true},
    [16583] = {Engineering = true},
    [17010] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Mining = true, Tailoring = true},
    [17011] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [17012] = {Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [17034] = {Enchanting = true},
    [17035] = {Enchanting = true},
    [17056] = {Engineering = true},
    [17194] = {Cooking = true},
    [17196] = {Cooking = true},
    [17202] = {Engineering = true},
    [17203] = {Blacksmithing = true},
    [18168] = {Engineering = true},
    [18240] = {Leatherworking = true, Tailoring = true},
    [18251] = {Leatherworking = true},
    [18255] = {Cooking = true},
    [18256] = {Alchemy = true, Enchanting = true},
    [18262] = {Blacksmithing = true},
    [18512] = {Enchanting = true, Leatherworking = true},
    [18562] = {Mining = true},
    [18567] = {Blacksmithing = true, Mining = true},
    [18631] = {Engineering = true},
    [18984] = {Engineering = true},
    [18986] = {Engineering = true},
    [19441] = {FirstAid = true},
    [19726] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [19767] = {Leatherworking = true},
    [19768] = {Leatherworking = true},
    [19774] = {Blacksmithing = true, Engineering = true},
    [19943] = {Alchemy = true},
    [20381] = {Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [20424] = {Cooking = true},
    [20498] = {Leatherworking = true},
    [20500] = {Leatherworking = true},
    [20501] = {Leatherworking = true},
    [20520] = {Blacksmithing = true, Tailoring = true},
    [20725] = {Blacksmithing = true, Enchanting = true, Engineering = true},
    [20867] = {Blacksmithing = true},
    [20868] = {Engineering = true},
    [20870] = {Engineering = true},
    [20871] = {Blacksmithing = true},
    [20872] = {Blacksmithing = true},
    [20873] = {Blacksmithing = true},
    [20874] = {Blacksmithing = true},
    [20875] = {Blacksmithing = true},
    [20876] = {Blacksmithing = true},
    [20877] = {Blacksmithing = true},
    [20878] = {Blacksmithing = true},
    [20879] = {Blacksmithing = true},
    [20881] = {Engineering = true},
    [20882] = {Blacksmithing = true},
    [21024] = {Cooking = true},
    [21071] = {Cooking = true},
    [21153] = {Cooking = true},
    [22202] = {Blacksmithing = true, Engineering = true},
    [22203] = {Blacksmithing = true, Mining = true},
    [22682] = {Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [23567] = {FirstAid = true},
    [211422] = {Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [213369] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [213370] = {Leatherworking = true},
    [213371] = {Alchemy = true},
    [213372] = {Leatherworking = true, Tailoring = true},
    [213373] = {Blacksmithing = true},
    [213376] = {Blacksmithing = true, Engineering = true, Leatherworking = true},
    [213378] = {Tailoring = true},
    [213379] = {Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [213381] = {Engineering = true},
    [213383] = {Blacksmithing = true, Engineering = true},
    [215430] = {Alchemy = true, Engineering = true},
    [220688] = {Alchemy = true, Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [220689] = {Engineering = true},
    [221021] = {Alchemy = true, Blacksmithing = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [221312] = {Alchemy = true},
    [227813] = {Cooking = true},
    [234003] = {Blacksmithing = true, Enchanting = true, Engineering = true},
    [234004] = {Blacksmithing = true, Enchanting = true},
    [234005] = {Enchanting = true, Engineering = true},
    [234006] = {Alchemy = true, Blacksmithing = true, Enchanting = true},
    [234007] = {Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [234008] = {Enchanting = true, Engineering = true, Tailoring = true},
    [234009] = {Engineering = true, Leatherworking = true, Tailoring = true},
    [234010] = {Alchemy = true, Enchanting = true, Engineering = true},
    [234011] = {Alchemy = true, Enchanting = true, Engineering = true},
    [234012] = {Alchemy = true, Enchanting = true, Engineering = true},
    [236656] = {Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [238737] = {Engineering = true},
    [238786] = {Engineering = true},
    [238787] = {Engineering = true},
    [238788] = {Engineering = true},
    [239016] = {Cooking = true},
    [239017] = {Cooking = true},
    [247786] = {Enchanting = true},
    [248815] = {Mining = true},
    [248819] = {Alchemy = true, Enchanting = true},
    [248820] = {Blacksmithing = true, Enchanting = true, Engineering = true},
    [248821] = {Alchemy = true},
    [248822] = {Alchemy = true, Blacksmithing = true, Enchanting = true, Engineering = true},
    [248823] = {Alchemy = true, Engineering = true},
    [248824] = {Leatherworking = true},
    [248825] = {Leatherworking = true},
    [249274] = {Alchemy = true, Enchanting = true},
    [249391] = {Alchemy = true, Enchanting = true, Engineering = true, Tailoring = true},
    [249399] = {Alchemy = true, Enchanting = true},
    [249409] = {Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
    [249410] = {Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true},
    [249424] = {Alchemy = true, Enchanting = true},
    [249425] = {Enchanting = true, Engineering = true},
    [249426] = {Engineering = true, Mining = true},
    [249427] = {Blacksmithing = true, Leatherworking = true, Tailoring = true},
    [249428] = {Engineering = true, Leatherworking = true, Tailoring = true},
    [249429] = {Engineering = true, Leatherworking = true, Tailoring = true},
    [249430] = {Enchanting = true, Engineering = true, Tailoring = true},
    [249431] = {Enchanting = true, Engineering = true, Tailoring = true},
    [249432] = {Blacksmithing = true, Enchanting = true, Engineering = true},
    [249726] = {Blacksmithing = true, Enchanting = true, Engineering = true},
    [249796] = {Cooking = true},
    [251290] = {Blacksmithing = true, Engineering = true},
    [251291] = {Alchemy = true, Blacksmithing = true, Engineering = true},
    [251524] = {Cooking = true},
    [252948] = {Cooking = true},
    [255007] = {Engineering = true},
    [255645] = {FirstAid = true},
    [260784] = {Engineering = true},
    [260794] = {Engineering = true},
    [260796] = {Engineering = true},
    [260799] = {Engineering = true},
    [260801] = {Engineering = true},
    [260804] = {Engineering = true},
    [260808] = {Engineering = true},
    [260813] = {Engineering = true},
    [260815] = {Engineering = true},
    [260823] = {Engineering = true},
    [272941] = {Cooking = true},
    [273125] = {Alchemy = true},
    [273127] = {Blacksmithing = true},
    [273128] = {Enchanting = true},
    [273129] = {Engineering = true},
    [273130] = {Leatherworking = true},
    [273131] = {Tailoring = true},
    [273295] = {Fishing = true},
    [274030] = {Blacksmithing = true, Enchanting = true, Engineering = true, Leatherworking = true, Tailoring = true},
}
